version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins-net 
    volumes:
      - jenkins-data:/var/jenkins_home
  
  node-app-jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-node-app-jenkins
    ports:
      - "9001:3000"
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge

volumes:
  jenkins-data:
